### ISSUE TITLE
Make API calls to Udacity API

### ISSUE THREAD

**Issue by rajatmw1999** [adavijit/BlogMan#26]
udacity provides API to fetch the data of particular courses based on a search query parameter.
Make udacity API calls in the back end based on different search criterias like domain(web dev, data science), stack(mern mean, flutter etc), university and authors.
Fetch the JSON data and display it.

**Comment by lakshyajit165** [comment]
I am interested in this issue.

**Comment by adityasanil** [comment]
Can I work on this?

**Comment by lakshyajit165** [comment]
I tried to access the API. But it turns out that coursera deprecated their catalog APIs in 2017. I get this message instead.
![Screenshot from 2020-03-04 19-07-22](https://user-images.githubusercontent.com/30868587/75885634-dc9ca400-5e4c-11ea-925e-9db94200a1db.png)

**Comment by rajatmw1999** [comment]
Wait, this means they dont provide APIs for their course information anymore??
Check out the web, i think there has to be another API. What is this Affiliate Program in this screenshot.
Try to make sure that you get a coursera API by reasearching a bit. If you can't get it, then go through the API of some other website that gives coding courses, like udacity or some other website.

**Comment by lakshyajit165** [comment]
Yeah. They don't provide APIs directly anymore. The screenshot above shows that, we can still access the coursera APIs, through their 'Affiliate program'. I tried applying for it, but a lot of details needed to be filled in. I thought the mentors should tell us how to proceed with that, otherwise, we could use APIs from other sites like Udemy, Udacity etc.

**Comment by rajatmw1999** [comment]
We are already using Udemy. We will need the coursera api as well. I suggest you enroll in the program and get the API keys.

**Comment by lakshyajit165** [comment]
Sure. Let me check out the details about it today.

**Comment by lakshyajit165** [comment]
So I checked this affiliate program. What I have understood is, they(coursera) want anyone who is requesting access to their APIs to adversite the courses on their website. And for that, they need the following details. Here is the screenshot of the entire page. The empty fields(ones where I could not understand what to fill in) are marked in red
Note: I intentionally blacked out my address fields because of privacy concerns.
![coursera_affiliate](https://user-images.githubusercontent.com/30868587/75895009-0a88e500-5e5b-11ea-94e8-39e54a12420e.png)

**Comment by rajatmw1999** [comment]
These details are not ready yet. If the form is not proceeding further, try udacity or some other website you might feel provide good quality material.

**Comment by lakshyajit165** [comment]
I looked into the Udacity Course Catalog API today, but it seems they don't provide a public documentation/website for their APIs too. But I learned that there might be a way to access the API through a website called rapiapi.com. I'm still looking into this.

**Comment by rajatmw1999** [comment]
okay. keep me posted.

**Comment by lakshyajit165** [comment]
Hi @rajatmw1999, I know it's kinda bummer, but udacity doesn't seem to make its course catalog apis public too. I found an old API though, but it gives 404 error now(seems to me that, this API was valid once but is now deprecated).

![Screenshot from 2020-03-06 19-22-54](https://user-images.githubusercontent.com/30868587/76090748-1fdc4b80-5fe2-11ea-880e-fd05a6a8d744.png)

**Comment by rajatmw1999** [comment]
@lakshyajit165 i will close this issue for now. Recently i have opened a few api course comparison issue, you can comment in one of them.. which is not assigned yet.

**Comment by rajatmw1999** [comment]
leave your comment in the edx.org api issue.
